const KEY='singmal_training_v8';
const OLD_KEYS=['sgmy_travel_v7_full','sgmy_travel_v6_sg_day1_2','sgmy_travel_v5_malaysia_first','sgmy_travel_v3'];
const packingBase=[
 ['📄 서류·연수',[['여권','유효기간 확인','필수'],['항공권·탑승권','앱 또는 PDF 저장','필수'],['호텔 예약 확인서','오프라인 저장 권장','필수'],['연수 안내사항 서류','일정·기관 방문 안내 등','필수'],['여행자보험 정보','가입한 경우','권장'],['입국·여행 관련 확인자료','출발 직전 최신 안내 확인','확인'],['여권 사본','분실 대비','권장']]],
 ['👔 의류',[['반팔 상의','4~5장','추천'],['얇은 하의','3~4벌','추천'],['세미정장','기관 방문·연수 행사 대비','필수'],['속옷','6~7세트','5박7일'],['양말','4~6켤레','추천'],['잠옷','1벌','추천'],['얇은 겉옷','실내 냉방 대비','추천'],['모자','햇빛 대비','선택']]],
 ['📝 연수 준비',[['메모지·노트','연수 내용 기록용','필수'],['볼펜·필기구','여분 포함','필수'],['명찰·기관 자료','제공받은 경우','확인'],['휴대용 파일·서류봉투','연수 자료 보관','권장']]],
 ['👟 신발·가방',[['편한 운동화','도보 이동용','추천'],['샌들 또는 슬리퍼','비 대비','추천'],['작은 크로스백','여권·휴대폰 보관','추천'],['접이식 보조가방','귀국 짐 증가 대비','추천']]],
 ['🧴 세면·위생',[['칫솔·치약','','기본'],['세안용품','','기본'],['기초 화장품','소용량 권장','기본'],['선크림','야외활동 대비','추천'],['물티슈·티슈','','추천'],['개인 위생용품','필요에 따라','선택']]],
 ['🌧️ 날씨 대비',[['접이식 우산','갑작스러운 비 대비','추천'],['얇은 우비','야외 일정이 많다면','선택'],['작은 수건','땀·비 대비','추천'],['방수 파우치','전자기기 보호','추천']]],
 ['🔌 전자기기',[['휴대폰','','필수'],['충전기','','필수'],['보조배터리','항공사 규정 확인','추천'],['멀티 충전 케이블','','추천'],['여행용 어댑터','숙소 콘센트 확인','추천'],['이어폰','','선택']]],
 ['💳 돈·결제',[['해외 결제 가능 카드','해외사용 설정 확인','필수'],['소액 현금','교통·소규모 결제 대비','추천'],['예비 카드','별도 보관','권장']]],
 ['💊 건강·개인용품',[['개인 복용약','필요한 경우','필수'],['기본 상비용품','개인에게 필요한 범위','권장'],['안경·렌즈','사용하는 경우','필수'],['마스크','필요 시','선택']]]
];
const scheduleBase=[
 {title:'DAY 1 · 싱가포르 도착',color:'#3b82f6',events:[{time:'',place:'인천국제공항',note:'출국 준비 및 탑승'},{time:'',place:'싱가포르 창이공항',note:'싱가포르 도착'},{time:'',place:'싱가포르 숙소',note:'이동 및 체크인'}]},
 {title:'DAY 2 · 싱가포르',color:'#06b6d4',events:[{time:'',place:'싱가포르 연수·방문 일정',note:'기관명과 시간을 직접 입력'},{time:'',place:'싱가포르 오후 일정',note:'연수 또는 문화 탐방'},{time:'',place:'싱가포르 저녁 일정',note:'장소와 시간을 직접 입력'}]},
 {title:'DAY 3 · 싱가포르 / 조호바루',color:'#14b8a6',events:[{time:'',place:'싱가포르',note:'오전 연수·방문 또는 체크아웃'},{time:'',place:'조호바루',note:'국경 이동 및 도착'},{time:'',place:'조호바루 숙소',note:'체크인 및 일정'}]},
 {title:'DAY 4 · 조호바루 / 말라카 / 쿠알라룸푸르',color:'#22c55e',events:[{time:'',place:'조호바루',note:'출발'},{time:'',place:'말라카',note:'기관 방문·문화 탐방·식사 등'},{time:'',place:'쿠알라룸푸르',note:'이동 및 체크인'}]},
 {title:'DAY 5 · 쿠알라룸푸르',color:'#eab308',events:[{time:'',place:'쿠알라룸푸르 연수·방문 일정',note:'기관명과 시간을 직접 입력'},{time:'',place:'쿠알라룸푸르 오후 일정',note:'연수 또는 문화 탐방'},{time:'',place:'쿠알라룸푸르 저녁 일정',note:'장소와 시간을 직접 입력'}]},
 {title:'DAY 6 · 쿠알라룸푸르 / 인천',color:'#f97316',events:[{time:'',place:'쿠알라룸푸르',note:'귀국 전 일정 및 체크아웃'},{time:'',place:'쿠알라룸푸르 국제공항',note:'공항 이동 및 출국'},{time:'',place:'인천국제공항',note:'귀국편'}]},
 {title:'DAY 7 · 인천',color:'#a855f7',events:[{time:'',place:'인천국제공항',note:'입국 및 수하물 수령'},{time:'',place:'귀가',note:'연수 종료'}]}
];
function makePacking(){let n=0;return packingBase.map(([category,items])=>({category,items:items.map(([name,meta,tag])=>({id:'p'+(++n),name,meta,tag,done:false}))}));}
function fresh(){return{departure:'',packing:makePacking(),schedule:structuredClone(scheduleBase)}}
function migrate(base){for(const key of OLD_KEYS){try{const old=JSON.parse(localStorage.getItem(key));if(!old)continue;if(old.departure)base.departure=old.departure;if(Array.isArray(old.packing)){const map=new Map();old.packing.forEach(g=>g.items?.forEach(i=>map.set(i.name,!!i.done)));base.packing.forEach(g=>g.items.forEach(i=>{if(map.has(i.name))i.done=map.get(i.name)}))}if(Array.isArray(old.schedule)&&old.schedule.length===7){old.schedule.forEach((d,i)=>{if(d.title)base.schedule[i].title=d.title;if(d.color)base.schedule[i].color=d.color;if(Array.isArray(d.events)&&d.events.length)base.schedule[i].events=d.events})}return base}catch{}}return base}
function load(){try{const x=JSON.parse(localStorage.getItem(KEY));if(x?.packing&&x?.schedule)return x}catch{}return migrate(fresh())}
let state=load(),pending=false,deferredPrompt=null,translateTimer=null,fxCache={};
const save=()=>localStorage.setItem(KEY,JSON.stringify(state));
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));
const fmtDate=d=>`${d.getMonth()+1}/${d.getDate()} (${['일','월','화','수','목','금','토'][d.getDay()]})`;
function tint(hex){let h=(hex||'#3b82f6').replace('#','');if(h.length===3)h=h.split('').map(x=>x+x).join('');return `rgba(${parseInt(h.slice(0,2),16)},${parseInt(h.slice(2,4),16)},${parseInt(h.slice(4,6),16)},.09)`}
function openMap(q){q=(q||'').trim();if(!q)return alert('먼저 장소를 입력해주세요.');window.open('https://www.google.com/maps/search/?api=1&query='+encodeURIComponent(q),'_blank','noopener')}

// Photos: saved locally in IndexedDB on this device.
const DB='singmal-training-photos-v1',STORE='photos';
function dbOpen(){return new Promise((ok,bad)=>{const r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:'id'})};r.onsuccess=()=>ok(r.result);r.onerror=()=>bad(r.error)})}
async function photoAll(day){const db=await dbOpen();return new Promise((ok,bad)=>{const r=db.transaction(STORE).objectStore(STORE).getAll();r.onsuccess=()=>ok(r.result.filter(x=>x.day===day).sort((a,b)=>a.createdAt-b.createdAt));r.onerror=()=>bad(r.error)})}
async function photoPut(x){const db=await dbOpen();return new Promise((ok,bad)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).put(x);tx.oncomplete=ok;tx.onerror=()=>bad(tx.error)})}
async function photoDel(id){const db=await dbOpen();return new Promise((ok,bad)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).delete(id);tx.oncomplete=ok;tx.onerror=()=>bad(tx.error)})}
async function photoClear(){const db=await dbOpen();return new Promise((ok,bad)=>{const tx=db.transaction(STORE,'readwrite');tx.objectStore(STORE).clear();tx.oncomplete=ok;tx.onerror=()=>bad(tx.error)})}
function compress(file){return new Promise((ok,bad)=>{const img=new Image(),url=URL.createObjectURL(file);img.onload=()=>{const max=1600,scale=Math.min(1,max/Math.max(img.width,img.height)),c=document.createElement('canvas');c.width=Math.round(img.width*scale);c.height=Math.round(img.height*scale);c.getContext('2d').drawImage(img,0,0,c.width,c.height);c.toBlob(b=>{URL.revokeObjectURL(url);b?ok(b):bad(new Error('이미지 저장 실패'))},'image/jpeg',.82)};img.onerror=()=>bad(new Error('이미지를 읽을 수 없습니다.'));img.src=url})}
async function addPhotos(day,files){for(const file of [...files].slice(0,10)){if(!file.type.startsWith('image/'))continue;const data=await compress(file);await photoPut({id:crypto.randomUUID?.()||('ph'+Date.now()+Math.random()),day,name:file.name,data,createdAt:Date.now()})}renderGallery(day)}
async function renderGallery(day){const root=document.querySelector(`[data-gallery="${day}"]`);if(!root)return;try{const photos=await photoAll(day);if(!photos.length){root.innerHTML='<div class="small">아직 저장된 사진이 없습니다.</div>';return}root.innerHTML='';photos.forEach(p=>{const url=URL.createObjectURL(p.data),el=document.createElement('div');el.className='photo';el.innerHTML=`<img alt="방문 사진"><button data-photo-del="${p.id}">✕</button>`;el.querySelector('img').src=url;el.querySelector('img').onload=()=>setTimeout(()=>URL.revokeObjectURL(url),1000);root.appendChild(el)});root.querySelectorAll('[data-photo-del]').forEach(b=>b.onclick=async e=>{if(confirm('이 사진을 삭제할까요?')){await photoDel(e.currentTarget.dataset.photoDel);renderGallery(day)}})}catch{root.innerHTML='<div class="small">사진 저장공간을 열 수 없습니다.</div>'}}

function updateDate(){const dep=document.getElementById('departure');dep.value=state.departure||'';const dd=document.getElementById('dday'),range=document.getElementById('triprange');if(!state.departure){dd.textContent='D-?';range.textContent='출발일을 입력하면 7일 일정 날짜가 자동으로 표시됩니다.';return}const s=new Date(state.departure+'T00:00:00'),today=new Date();today.setHours(0,0,0,0);const diff=Math.round((s-today)/86400000);dd.textContent=diff>0?'D-'+diff:diff===0?'D-DAY':'D+'+Math.abs(diff);const e=new Date(s);e.setDate(s.getDate()+6);range.textContent=`연수 기간: ${fmtDate(s)} ~ ${fmtDate(e)} · 5박 7일`}

function renderPacking(){const q=document.getElementById('search').value.trim().toLowerCase(),root=document.getElementById('packingCards');root.innerHTML='';let visible=0;state.packing.forEach(g=>{const items=g.items.filter(i=>(i.name+' '+i.meta+' '+i.tag).toLowerCase().includes(q)&&(!pending||!i.done));if(!items.length)return;visible+=items.length;const card=document.createElement('div');card.className='card';card.innerHTML=`<div class="cathead"><b>${esc(g.category)}</b><span class="muted">${g.items.filter(i=>i.done).length}/${g.items.length}</span></div><div class="list"></div>`;const list=card.querySelector('.list');items.forEach(i=>{const row=document.createElement('label');row.className='item'+(i.done?' done':'');row.innerHTML=`<input type="checkbox" data-id="${i.id}" ${i.done?'checked':''}><div><div class="iname">${esc(i.name)}</div>${i.meta?`<div class="imeta">${esc(i.meta)}</div>`:''}</div><span class="tag">${esc(i.tag)}</span>`;list.appendChild(row)});root.appendChild(card)});if(!visible)root.innerHTML='<div class="card" style="padding:20px;text-align:center">조건에 맞는 준비물이 없습니다.</div>';root.querySelectorAll('[data-id]').forEach(c=>c.onchange=e=>{state.packing.forEach(g=>g.items.forEach(i=>{if(i.id===e.target.dataset.id)i.done=e.target.checked}));save();renderPacking()});const all=state.packing.flatMap(g=>g.items),done=all.filter(i=>i.done).length,p=all.length?Math.round(done/all.length*100):0;document.getElementById('summary').textContent=`${done} / ${all.length}개 준비 완료`;document.getElementById('pct').textContent=p+'%';document.getElementById('bar').style.width=p+'%';const sel=document.getElementById('newCategory'),cur=sel.value;sel.innerHTML=state.packing.map((g,i)=>`<option value="${i}">${esc(g.category)}</option>`).join('');if(cur)sel.value=cur}

function renderSchedule(){const root=document.getElementById('days'),start=state.departure?new Date(state.departure+'T00:00:00'):null;root.innerHTML='';state.schedule.forEach((day,di)=>{const date=start?(()=>{const d=new Date(start);d.setDate(start.getDate()+di);return fmtDate(d)})():'날짜 미정';const card=document.createElement('div');card.className='card daycard';card.style.setProperty('--day-color',day.color);card.style.setProperty('--day-tint',tint(day.color));card.innerHTML=`<div class="daytop"><div class="daymain"><input class="daytitle" data-title="${di}" value="${esc(day.title)}"><div class="daydate">${date}</div></div><label class="colorpick">색상 <input type="color" data-color="${di}" value="${esc(day.color)}"></label></div><div class="events"></div><button class="addevent" data-add="${di}">+ 일정 추가</button><div class="photosection"><div class="photorow"><b>📷 방문 사진</b><button class="smallbtn" data-photo="${di}">+ 사진 추가</button></div><input class="photoinput" type="file" accept="image/*" multiple data-file="${di}"><div class="gallery" data-gallery="${di}"></div></div>`;const ev=card.querySelector('.events');day.events.forEach((x,ei)=>{const row=document.createElement('div');row.className='event';row.innerHTML=`<input type="time" data-k="time" data-d="${di}" data-e="${ei}" value="${esc(x.time)}"><div class="eventmain"><input data-k="place" data-d="${di}" data-e="${ei}" value="${esc(x.place)}" placeholder="장소/일정"><textarea data-k="note" data-d="${di}" data-e="${ei}" placeholder="메모">${esc(x.note)}</textarea><div class="eventactions"><button class="smallbtn" data-move="${di}:${ei}:-1" ${ei===0?'disabled':''}>↑ 위로</button><button class="smallbtn" data-move="${di}:${ei}:1" ${ei===day.events.length-1?'disabled':''}>↓ 아래로</button><button class="smallbtn mapbtn" data-map="${di}:${ei}">📍 지도</button><button class="smallbtn danger" data-del="${di}:${ei}">✕ 삭제</button></div></div>`;ev.appendChild(row)});root.appendChild(card)});
 root.querySelectorAll('[data-title]').forEach(x=>x.oninput=e=>{state.schedule[+e.target.dataset.title].title=e.target.value;save()});root.querySelectorAll('[data-color]').forEach(x=>x.oninput=e=>{state.schedule[+e.target.dataset.color].color=e.target.value;save();renderSchedule()});root.querySelectorAll('[data-k]').forEach(x=>x.oninput=e=>{const d=+e.target.dataset.d,i=+e.target.dataset.e;state.schedule[d].events[i][e.target.dataset.k]=e.target.value;save()});root.querySelectorAll('[data-move]').forEach(b=>b.onclick=e=>{const[d,i,delta]=e.currentTarget.dataset.move.split(':').map(Number),arr=state.schedule[d].events,n=i+delta;if(n<0||n>=arr.length)return;[arr[i],arr[n]]=[arr[n],arr[i]];save();renderSchedule()});root.querySelectorAll('[data-map]').forEach(b=>b.onclick=e=>{const[d,i]=e.currentTarget.dataset.map.split(':').map(Number);openMap(state.schedule[d].events[i].place)});root.querySelectorAll('[data-del]').forEach(b=>b.onclick=e=>{const[d,i]=e.currentTarget.dataset.del.split(':').map(Number);if(confirm('이 일정을 삭제할까요?')){state.schedule[d].events.splice(i,1);save();renderSchedule()}});root.querySelectorAll('[data-add]').forEach(b=>b.onclick=e=>{state.schedule[+e.currentTarget.dataset.add].events.push({time:'',place:'새 일정',note:''});save();renderSchedule()});root.querySelectorAll('[data-photo]').forEach(b=>b.onclick=e=>document.querySelector(`[data-file="${e.currentTarget.dataset.photo}"]`).click());root.querySelectorAll('[data-file]').forEach(f=>f.onchange=async e=>{await addPhotos(+e.currentTarget.dataset.file,e.currentTarget.files);e.currentTarget.value=''});state.schedule.forEach((_,i)=>renderGallery(i))}

const FX=['KRW','USD','SGD','MYR'],FXN={KRW:'대한민국 원',USD:'미국 달러',SGD:'싱가포르 달러',MYR:'말레이시아 링깃'},SYM={KRW:'₩',USD:'$',SGD:'S$',MYR:'RM'};
async function rate(base,quote,force=false){if(base===quote)return{rate:1,date:''};const k=base+'_'+quote;if(!force&&fxCache[k]&&Date.now()-fxCache[k].time<600000)return fxCache[k].data;const r=await fetch(`https://api.frankfurter.dev/v2/rate/${base}/${quote}`);if(!r.ok)throw new Error('환율 정보를 불러오지 못했습니다.');const d=await r.json();if(typeof d.rate!=='number')throw new Error('환율 응답 오류');const x={rate:d.rate,date:d.date||''};fxCache[k]={time:Date.now(),data:x};return x}
const money=(v,c)=>new Intl.NumberFormat('ko-KR',{maximumFractionDigits:c==='KRW'?0:2}).format(v);
async function updateFX(force=false){const amount=parseFloat(document.getElementById('fxAmount').value||0),base=document.getElementById('fxBase').value,root=document.getElementById('fxResults'),status=document.getElementById('fxStatus');root.innerHTML=FX.map(c=>`<div class="fxresult"><div class="fxcode">${c}</div><div id="fx_${c}" class="fxvalue">...</div><div class="fxname">${FXN[c]}</div></div>`).join('');status.className='status';status.textContent='최신 기준환율 계산 중...';try{const data=await Promise.all(FX.map(async c=>[c,await rate(base,c,force)]));let date='';data.forEach(([c,d])=>{document.getElementById('fx_'+c).textContent=`${SYM[c]} ${money(amount*d.rate,c)}`;if(d.date)date=d.date});status.textContent=`기준 ${base}${date?' · 환율 기준일 '+date:''} · 참고용 기준환율`}catch(e){status.className='status error';status.textContent=e.message+' 인터넷 연결을 확인해주세요.'}}

const bytes=s=>new TextEncoder().encode(s).length;
async function translate(){const text=document.getElementById('translateInput').value.trim(),s=document.getElementById('sourceLang').value,t=document.getElementById('targetLang').value,out=document.getElementById('translateOutput');if(!text){out.textContent='번역 결과가 여기에 표시됩니다.';return}if(s===t){out.textContent=text;return}if(bytes(text)>480){out.textContent='짧은 문장으로 나누어 입력해주세요.';return}out.textContent='번역 중...';try{const r=await fetch(`https://api.mymemory.translated.net/get?q=${encodeURIComponent(text)}&langpair=${s}%7C${t}&mt=1`);if(!r.ok)throw new Error('번역 서비스를 이용할 수 없습니다.');const d=await r.json(),tr=d?.responseData?.translatedText;if(!tr)throw new Error('번역 결과를 받지 못했습니다.');out.textContent=tr}catch(e){out.textContent=e.message+' 인터넷 연결을 확인해주세요.'}}
function autoTranslate(){clearTimeout(translateTimer);translateTimer=setTimeout(translate,750)}

// UI events
document.getElementById('departure').onchange=e=>{state.departure=e.target.value;save();updateDate();renderSchedule()};
document.querySelectorAll('.tab').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(b.dataset.page).classList.add('active');if(b.dataset.page==='currency')updateFX()});
document.getElementById('search').oninput=renderPacking;document.getElementById('pendingBtn').onclick=e=>{pending=!pending;e.target.textContent=pending?'전체 보기':'미완료만';renderPacking()};document.getElementById('addItemBtn').onclick=()=>{const inp=document.getElementById('newItem'),name=inp.value.trim();if(!name)return;state.packing[+document.getElementById('newCategory').value].items.push({id:'c'+Date.now(),name,meta:'직접 추가',tag:'사용자',done:false});inp.value='';save();renderPacking()};document.getElementById('newItem').onkeydown=e=>{if(e.key==='Enter')document.getElementById('addItemBtn').click()};document.getElementById('checkAllBtn').onclick=()=>{const all=state.packing.flatMap(g=>g.items),v=!all.every(i=>i.done);state.packing.forEach(g=>g.items.forEach(i=>i.done=v));save();renderPacking()};document.getElementById('copyBtn').onclick=async()=>{let t=['싱말연수',state.departure?`출발일: ${state.departure}`:'출발일: 미정',''];state.schedule.forEach(d=>{t.push(d.title);d.events.forEach(e=>t.push(`${e.time||'--:--'} ${e.place}${e.note?' - '+e.note:''}`));t.push('')});try{await navigator.clipboard.writeText(t.join('\n'));alert('일정을 복사했습니다.')}catch{}};document.getElementById('resetBtn').onclick=async()=>{if(confirm('출발일, 준비물 체크, 일정과 저장 사진을 모두 초기화할까요?')){state=fresh();save();try{await photoClear()}catch{}updateDate();renderPacking();renderSchedule()}};
document.getElementById('fxAmount').oninput=()=>updateFX();document.getElementById('fxBase').onchange=()=>updateFX();document.getElementById('fxRefresh').onclick=()=>{fxCache={};updateFX(true)};
document.getElementById('translateInput').oninput=autoTranslate;document.getElementById('sourceLang').onchange=autoTranslate;document.getElementById('targetLang').onchange=autoTranslate;document.getElementById('translateBtn').onclick=translate;document.getElementById('swapLang').onclick=()=>{const s=document.getElementById('sourceLang'),t=document.getElementById('targetLang'),v=s.value;s.value=t.value;t.value=v;autoTranslate()};document.getElementById('copyTranslation').onclick=async()=>{try{await navigator.clipboard.writeText(document.getElementById('translateOutput').textContent);alert('번역 결과를 복사했습니다.')}catch{}};document.getElementById('clearTranslation').onclick=()=>{document.getElementById('translateInput').value='';document.getElementById('translateOutput').textContent='번역 결과가 여기에 표시됩니다.'};document.querySelectorAll('.phrase').forEach(b=>b.onclick=e=>{document.getElementById('sourceLang').value='ko';document.getElementById('translateInput').value=e.currentTarget.textContent;autoTranslate()});
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;document.getElementById('installBanner').classList.add('show')});document.getElementById('installBtn').onclick=async()=>{if(!deferredPrompt)return;deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;document.getElementById('installBanner').classList.remove('show')};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('sw.js'));
save();updateDate();renderPacking();renderSchedule();updateFX();
